import 'jquery/dist/jquery.js'
import 'semantic-ui/dist/semantic.js'
import 'prism/prism.js'
import 'prism/components/prism-python.js'
import 'prism/plugins/highlight-keywords/prism-highlight-keywords.js'
import 'prism/plugins/line-highlight/prism-line-highlight.js'